### ISSUE TITLE
Blank screen with basic example

### ISSUE THREAD

**Issue by brgcode** [leon-thomm/ryvencore-qt#19]
hi,

i am trying to run the basic example (the one from the README of this repo), but i only get a blank screen.
<img width="912" alt="Screenshot 2022-01-24 at 12 34 56" src="https://user-images.githubusercontent.com/29653489/150776115-40447262-610c-4ef0-aafa-949ce07ad3a5.png">

any ideas about what the problem might be?
i just copy-pasted the code from the README and i don't get any errors...

thanks!

**Comment by leon-thomm** [comment]
well, I think you are seeing exactly what you're supposed to :) a window with a running ryvencore session and an empty graph scene. if you right-click into the scene a dialog for placing nodes should pop up

**Comment by brgcode** [comment]
ha, awesome :)
thanks for the quick reply!
