### ISSUE TITLE
Error when connecting to dtype inputs

### ISSUE THREAD

**Issue by RZechlin** [leon-thomm/ryvencore-qt#7]
Hi,
I hope it is correct to report this issue here, although it occurred while using Ryven. 
When connecting to a node with, for example, a `dtype=dtypes.Integer()`, an error can be thrown if the type of the input does not match the expectation (Integer). 
While this generally makes sense, it makes building macros with one of the inputs being used in a for loop impossible. The data type of the input will be None.
When a file is saved that has one of these "illegal" connections, it also becomes impossible to open in Ryven as the error is thrown during the loading process as well and will shut down the process. 

```
Traceback (most recent call last):
  File "C:\Users\test\.virtualenvs\Ryven\lib\site-packages\ryvencore_qt\src\FlowView.py", line 876, in add_connection

item.inp_item.port_connected()

  File "C:\Users\test\.virtualenvs\Ryven\lib\site-packages\ryvencore_qt\src\PortItem.py", line 168, in port_connected

self._port_val_updated(self.port.val)

  File "C:\Users\test\.virtualenvs\Ryven\lib\site-packages\ryvencore_qt\src\PortItem.py", line 179, in _port_val_updated

self.widget.val_update_event(val)

  File "C:\Users\test\.virtualenvs\Ryven\lib\site-packages\ryvencore_qt\src\PortItemInputWidgets.py", line 285, in val_update_event

self.setValue(val)

TypeError
:
'PySide2.QtWidgets.QSpinBox.setValue' called with wrong argument types:
  PySide2.QtWidgets.QSpinBox.setValue(NoneType)
Supported signatures:
  PySide2.QtWidgets.QSpinBox.setValue(int)
```

Is there a way to alert to this error but still allow for the creation of flows?

**Comment by leon-thomm** [comment]
Thank you very much, that wasn't intended.

Should be fixed in 0f623c4e61421e679ba1b394ce6267dff7359176 (master branch) could you try again?

**Comment by leon-thomm** [comment]
for documentation purposes: I added the `show()` method to the `DType_IW_Base`, the current implementations just print occuring errors to `InfoMsgs`, so if a node's behavior isn't as expected due to harmful type conversions in dtype widgets, this can be seen easily when enabling  debugging messages

**Comment by leon-thomm** [comment]
I will upload a new version to PyPi later

**Comment by RZechlin** [comment]
Thank you. However, the save file won't load if there is an error in one of the scripts.
It works fine as long the error is just in one of the macros.
To reproduce: Connect a "val" node with e.g. `[1,2,3]` to a "for each" node. After saving and closing the program, I am not able to open the save file. The process stops after 
```
TypeError: 'PySide2.QtWidgets.QSpinBox.setValue' called with wrong argument types:
  PySide2.QtWidgets.QSpinBox.setValue(NoneType)
Supported signatures:
  PySide2.QtWidgets.QSpinBox.setValue(int)
```

**Comment by leon-thomm** [comment]
It works with the fixed version on my system. Did you install it? (it should be `pip install ryvencore-qt --upgrade`)
If so, could you send me this project file so I can try?

**Comment by RZechlin** [comment]
It is now working. I'm sorry, I must have forgotten updating the library.

I can open files with any of these related errors now.
